# Generated by Django 5.1.7 on 2025-03-24 16:11

import django.db.models.deletion
import inbox.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_one_group', models.CharField(default=None, max_length=250, null=True)),
                ('person_two_group', models.CharField(default=None, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message', models.DateTimeField(auto_now=True)),
                ('has_unread_msg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.BigIntegerField()),
                ('receiver', models.BigIntegerField()),
                ('sender_group', models.CharField(default=None, max_length=250, null=True)),
                ('receiver_group', models.CharField(default=None, max_length=250, null=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inbox.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='MessageDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(default=None, null=True)),
                ('if_delivered', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inbox.message')),
            ],
        ),
        migrations.CreateModel(
            name='MessagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=inbox.models.saveMessagePhoto)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inbox.message')),
            ],
        ),
    ]
