# Generated by Django 5.1.7 on 2025-04-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_remove_conversation_has_unread_msg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationstatus',
            name='last_receiver_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
