# Generated by Django 5.1.7 on 2025-03-10 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_country_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='user',
        ),
        migrations.AddField(
            model_name='country',
            name='users',
            field=models.ManyToManyField(related_name='countries', to=settings.AUTH_USER_MODEL),
        ),
    ]
