# Generated by Django 5.1.7 on 2025-03-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_remove_country_user_country_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(verbose_name=10)),
                ('name', models.CharField(verbose_name=100)),
            ],
        ),
    ]
