# Generated by Django 5.1.7 on 2025-03-10 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyer_post', '0001_initial'),
        ('country', '0004_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_msg', models.TextField()),
                ('estimated_delivery_time', models.IntegerField()),
                ('price', models.FloatField()),
                ('buyer_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer_post.buyerpost')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.currency')),
            ],
        ),
    ]
