# Generated by Django 5.1.7 on 2025-03-13 13:15

import django.db.models.deletion
import seller_offer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_offer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerSamplePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=seller_offer.models.saveSamplePhoto)),
                ('seller_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_offer.selleroffer')),
            ],
        ),
    ]
