# Generated by Django 5.1.7 on 2025-04-12 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_offer', '0004_alter_selleroffer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleroffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
