# Generated by Django 5.1.7 on 2025-04-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='total_offers',
            field=models.BigIntegerField(default=0),
        ),
    ]
