# Generated by Django 5.1.7 on 2025-04-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_total_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='if_read',
            field=models.BooleanField(default=False),
        ),
    ]
