# Generated by Django 5.1.7 on 2025-04-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_if_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post_code_name',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
