# Generated by Django 5.1.7 on 2025-03-12 00:12

import buyer_post.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_post', '0002_buyerpost_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerSamplePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=buyer_post.models.saveSamplePhoto)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer_post.buyerpost')),
            ],
        ),
    ]
