# Generated by Django 5.1.7 on 2025-04-08 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_post', '0004_alter_buyersamplephoto_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyerpost',
            name='if_published',
            field=models.BooleanField(default=True),
        ),
    ]
