# Generated by Django 5.1.7 on 2025-04-08 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_post', '0005_buyerpost_created_at_buyerpost_if_published'),
        ('country', '0004_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerpost',
            name='country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.country'),
        ),
        migrations.AlterField(
            model_name='buyerpost',
            name='state_district',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
