# Generated by Django 5.1.7 on 2025-04-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_post', '0006_alter_buyerpost_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerpost',
            name='deadline',
            field=models.IntegerField(default=1),
        ),
    ]
