# Generated by Django 5.1.7 on 2025-04-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_post', '0007_alter_buyerpost_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerpost',
            name='post_code_name',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
