# Generated by Django 5.1.7 on 2025-03-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0002_user_security_code_user_security_code_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='security_code_generated',
            field=models.BooleanField(default=False),
        ),
    ]
