# Generated by Django 5.1.7 on 2025-03-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0003_alter_user_security_code_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channel_group_name',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
