# Generated by Django 5.1.7 on 2025-03-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0004_user_channel_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='websockets_opened',
            field=models.IntegerField(default=0),
        ),
    ]
