# Generated by Django 5.1.7 on 2025-04-22 17:18

import useraccounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0006_user_is_verified_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='profile_photos/default.png', upload_to=useraccounts.models.save_profile_photo),
        ),
    ]
