from django.shortcuts import render, HttpResponse
from .models import Country, Currency
# Create your views here.
def populateCountriesTable(request):
    if Country.objects.count() == 0:
        countries = ['Andorra', 'Albania', 'Austria', 'Belgium', 'Bulgaria', 'Belarus', 'Czech Republic', 'Germany', 'Denmark', 'Estonia', 'Finland', 'France', 'Greece', 'Hungary', 'Republic of Ireland', 'Iceland', 'Italy', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Latvia', 'Macedonia', 'Malta', 'Kingdom of the Netherlands', 'Norway', 'Palestine', 'Poland', 'Portugal', 'Romania', 'Russia', 'Sweden', 'Slovenia', 'Slovakia', 'San Marino', 'Ukraine', 'Vatican City', 'Bosnia and Herzegovina', 'Croatia', 'Moldova', 'Monaco', 'Montenegro', 'Serbia', 'Spain', 'Switzerland', 'United Kingdom','Afghanistan', 'Armenia', 'Azerbaijan', 'Bangladesh', 'Bahrain', 'Brunei Darussalam', 'Bhutan', "People's Republic of China", 'Cyprus', 'Georgia', 'Indonesia', 'Israel', 'India', 'Iraq', 'Iran', 'Jordan', 'Japan', 'Kyrgyzstan', 'North Korea', 'South Korea', 'Kuwait', 'Lebanon', 'Myanmar', 'Mongolia', 'Maldives', 'Malaysia', 'Nepal', 'Oman', 'Philippines', 'Pakistan', 'Qatar', 'Saudi Arabia', 'Singapore', 'Syria', 'Thailand', 'Tajikistan', 'Turkmenistan', 'Turkey', 'Uzbekistan', 'Vietnam', 'Yemen', 'Cambodia', 'East Timor', 'Kazakhstan', 'Laos', 'Sri Lanka', 'United Arab Emirates','Antigua and Barbuda', 'Barbados', 'Bahamas', 'Belize', 'Canada', 'Costa Rica', 'Cuba', 'Dominica', 'Dominican Republic', 'Guatemala', 'Haiti', 'Honduras', 'Jamaica', 'Mexico', 'Nicaragua', 'Panama', 'Trinidad and Tobago', 'United States', 'El Salvador', 'Grenada', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines','Angola', 'Burkina Faso', 'Burundi', 'Benin', 'Botswana', 'Democratic Republic of the Congo', 'Republic of the Congo', 'Ivory Coast', 'Cameroon', 'Cape Verde', 'Djibouti', 'Egypt', 'Eritrea', 'Ethiopia', 'Gabon', 'Ghana', 'The Gambia', 'Guinea', 'Guinea-Bissau', 'Kenya', 'Liberia', 'Lesotho', 'Libya', 'Madagascar', 'Mali', 'Mauritania', 'Mauritius', 'Malawi', 'Mozambique', 'Namibia', 'Niger', 'Nigeria', 'Rwanda', 'Seychelles', 'Sudan', 'Sierra Leone', 'Senegal', 'Somalia', 'Sao Tome and Principe', 'Togo', 'Tunisia', 'Tanzania', 'Uganda', 'Zambia', 'Zimbabwe', 'Algeria', 'Central African Republic', 'Chad', 'Comoros', 'Equatorial Guinea', 'Morocco', 'South Africa', 'Swaziland','Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador', 'Guyana', 'Peru', 'Paraguay', 'Suriname', 'Uruguay', 'Venezuela','Australia', 'Fiji', 'Kiribati', 'Marshall Islands', 'Nauru', 'New Zealand', 'Papua New Guinea', 'Palau', 'Solomon Islands', 'Tonga', 'Tuvalu', 'Vanuatu', 'Federated States of Micronesia', 'Samoa']
        countries.sort()
        country_list = []
        for c in countries:
            country_list.append((Country(name=c)))
        Country.objects.bulk_create(country_list)
        return HttpResponse('Country table updated.')
    else:
        return HttpResponse("Country table already contains data.")
    

def populateCurrenciesTable(request):
    if Currency.objects.count() == 0:
        currencies = (	("AFN", "Afghani"),
	    ("DZD", "Algerian Dinar"),
	    ("ARS", "Argentine Peso"),
	    ("AMD", "Armenian Dram"),
	    ("AWG", "Aruban Guilder"),
	    ("AUD", "Australian Dollar"),
	    ("AZN", "Azerbaijanian Manat"),
	    ("BSD", "Bahamian Dollar"),
	    ("BHD", "Bahraini Dinar"),
	    ("THB", "Baht"),
	    ("PAB", "Balboa"),
	    ("BBD", "Barbados Dollar"),
	    ("BYR", "Belarussian Ruble"),
	    ("BZD", "Belize Dollar"),
	    ("BMD", "Bermudian Dollar"),
	    ("VEF", "Bolivar Fuerte"),
	    ("BOB", "Boliviano"),
	    ("BRL", "Brazilian Real"),
	    ("BND", "Brunei Dollar"),
	    ("BGN", "Bulgarian Lev"),
	    ("BIF", "Burundi Franc"),
	    ("CAD", "Canadian Dollar"),
	    ("CVE", "Cape Verde Escudo"),
	    ("KYD", "Cayman Islands Dollar"),
	    ("GHS", "Cedi"),
	    ("CLP", "Chilean Peso"),
	    ("COP", "Colombian Peso"),
	    ("KMF", "Comoro Franc"),
	    ("CDF", "Congolese Franc"),
	    ("BAM", "Convertible Mark"),
	    ("NIO", "Cordoba Oro"),
	    ("CRC", "Costa Rican Colon"),
	    ("HRK", "Croatian Kuna"),
	    ("CUP", "Cuban Peso"),
	    ("CZK", "Czech Koruna"),
	    ("GMD", "Dalasi"),
	    ("DKK", "Danish Krone"),
	    ("MKD", "Denar"),
	    ("DJF", "Djibouti Franc"),
	    ("STD", "Dobra"),
	    ("DOP", "Dominican Peso"),
	    ("VND", "Dong"),
	    ("XCD", "East Caribbean Dollar"),
	    ("EGP", "Egyptian Pound"),
	    ("SVC", "El Salvador Colon"),
	    ("ETB", "Ethiopian Birr"),
	    ("EUR", "Euro"),
	    ("FKP", "Falkland Islands Pound"),
	    ("FJD", "Fiji Dollar"),
	    ("HUF", "Forint"),
	    ("GIP", "Gibraltar Pound"),
	    ("XAU", "Gold"),
	    ("HTG", "Gourde"),
	    ("PYG", "Guarani"),
	    ("GNF", "Guinea Franc"),
	    ("GYD", "Guyana Dollar"),
	    ("HKD", "Hong Kong Dollar"),
	    ("UAH", "Hryvnia"),
	    ("ISK", "Iceland Krona"),
	    ("INR", "Indian Rupee"),
	    ("IRR", "Iranian Rial"),
	    ("IQD", "Iraqi Dinar"),
	    ("JMD", "Jamaican Dollar"),
	    ("JOD", "Jordanian Dinar"),
	    ("KES", "Kenyan Shilling"),
	    ("PGK", "Kina"),
	    ("LAK", "Kip"),
	    ("KWD", "Kuwaiti Dinar"),
	    ("MWK", "Kwacha"),
	    ("AOA", "Kwanza"),
	    ("MMK", "Kyat"),
	    ("GEL", "Lari"),
	    ("LVL", "Latvian Lats"),
	    ("LBP", "Lebanese Pound"),
	    ("ALL", "Lek"),
	    ("HNL", "Lempira"),
	    ("SLL", "Leone"),
	    ("RON", "Leu"),
	    ("LRD", "Liberian Dollar"),
	    ("LYD", "Libyan Dinar"),
	    ("SZL", "Lilangeni"),
	    ("LTL", "Lithuanian Litas"),
	    ("LSL", "Loti"),
	    ("MGA", "Malagasy Ariary"),
	    ("MYR", "Malaysian Ringgit"),
	    ("MUR", "Mauritius Rupee"),
	    ("MZN", "Metical"),
	    ("MXN", "Mexican Peso"),
	    ("MDL", "Moldovan Leu"),
	    ("MAD", "Moroccan Dirham"),
	    ("BOV", "Mvdol"),
	    ("NGN", "Naira"),
	    ("ERN", "Nakfa"),
	    ("NAD", "Namibia Dollar"),
	    ("NPR", "Nepalese Rupee"),
	    ("ANG", "Netherlands Antillean Guilder"),
	    ("ILS", "New Israeli Sheqel"),
	    ("TMT", "New Manat"),
	    ("TWD", "New Taiwan Dollar"),
	    ("NZD", "New Zealand Dollar"),
	    ("BTN", "Ngultrum"),
	    ("KPW", "North Korean Won"),
	    ("NOK", "Norwegian Krone"),
	    ("PEN", "Nuevo Sol"),
	    ("MRO", "Ouguiya"),
	    ("PKR", "Pakistan Rupee"),
	    ("XPD", "Palladium"),
	    ("MOP", "Pataca"),
	    ("TOP", "Pa’anga"),
	    ("CUC", "Peso Convertible"),
	    ("UYU", "Peso Uruguayo"),
	    ("PHP", "Philippine Peso"),
	    ("XPT", "Platinum"),
	    ("GBP", "Pound Sterling"),
	    ("BWP", "Pula"),
	    ("QAR", "Qatari Rial"),
	    ("GTQ", "Quetzal"),
	    ("ZAR", "Rand"),
	    ("OMR", "Rial Omani"),
	    ("KHR", "Riel"),
	    ("MVR", "Rufiyaa"),
	    ("IDR", "Rupiah"),
	    ("RUB", "Russian Ruble"),
	    ("RWF", "Rwanda Franc"),
	    ("SHP", "Saint Helena Pound"),
	    ("SAR", "Saudi Riyal"),
	    ("RSD", "Serbian Dinar"),
	    ("SCR", "Seychelles Rupee"),
	    ("XAG", "Silver"),
	    ("SGD", "Singapore Dollar"),
	    ("SBD", "Solomon Islands Dollar"),
	    ("KGS", "Som"),
	    ("SOS", "Somali Shilling"),
	    ("TJS", "Somoni"),
	    ("ZAR", "South African Rand"),
	    ("LKR", "Sri Lanka Rupee"),
	    ("XSU", "Sucre"),
	    ("SDG", "Sudanese Pound"),
	    ("SRD", "Surinam Dollar"),
	    ("SEK", "Swedish Krona"),
	    ("CHF", "Swiss Franc"),
	    ("SYP", "Syrian Pound"),
	    ("BDT", "Taka"),
	    ("WST", "Tala"),
	    ("TZS", "Tanzanian Shilling"),
	    ("KZT", "Tenge"),
	    ("TTD", "Trinidad and Tobago Dollar"),
	    ("MNT", "Tugrik"),
	    ("TND", "Tunisian Dinar"),
	    ("TRY", "Turkish Lira"),
	    ("AED", "UAE Dirham"),
	    ("USD", "US Dollar"),
	    ("UGX", "Uganda Shilling"),
	    ("COU", "Unidad de Valor Real"),
	    ("CLF", "Unidades de fomento"),
	    ("UYI", "Uruguay Peso en Unidades Indexadas (URUIURUI)"),
	    ("UZS", "Uzbekistan Sum"),
	    ("VUV", "Vatu"),
	    ("KRW", "Won"),
	    ("YER", "Yemeni Rial"),
	    ("JPY", "Yen"),
	    ("CNY", "Yuan Renminbi"),
	    ("ZMK", "Zambian Kwacha"),
	    ("ZWL", "Zimbabwe Dollar"),
	    ("PLN", "Zloty"))
        currency_list = []
        for c in currencies:
            currency = Currency(code=c[0], name=c[1])
            currency_list.append(currency)
        Currency.objects.bulk_create(currency_list)
        return HttpResponse("Currency table populated.")
    else:
        return HttpResponse("Currency table is already populated")